/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.*;
import java.net.*;
import javax.swing.JOptionPane;
//import java.sql.*;
/**
 *
 * @author pengbitao
 */
public class RegisterAndPasswordModifyClientJFrame extends javax.swing.JFrame {
    //套接字设计
    private Socket socket = null;
    //定义字符输入流和输出流
    private PrintWriter pw ;
    private BufferedReader br;
    /**
     * Creates new form RegisterAndPasswordCorrect
     */
    public RegisterAndPasswordModifyClientJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel1.setText("用户注册");

        jLabel2.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel2.setText("用户修改密码");

        jLabel3.setText("服务器地址：");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("端口号：");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("学     号：");

        jTextField3.setEnabled(false);

        jLabel6.setText("姓  名：");

        jTextField4.setEnabled(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setText("班     级：");

        jLabel8.setText("邮  箱：");

        jTextField6.setEnabled(false);

        jButton1.setText("注册");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("退出");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("连接");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("学     号：");

        jTextField7.setEnabled(false);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel10.setText("邮  箱：");

        jLabel11.setText("旧密码：");

        jPasswordField1.setEnabled(false);

        jTextField8.setEnabled(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel12.setText("新密码：");

        jPasswordField2.setEnabled(false);
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });

        jLabel13.setText("新密码（再次输入）：");

        jPasswordField3.setEnabled(false);

        jButton4.setText("修改密码");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel14.setText("连接服务器");

        jButton5.setText("退出");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MON345", "MON91011", "THU345", "THU121314" }));
        jComboBox1.setEnabled(false);

        jLabel17.setText("实际 班级：");

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel18.setText("（如：2015计算机1班）");

        jLabel19.setText("（只支持163.com邮箱）");

        jLabel20.setText("（密码要求8-12位，至少包含一位数字，一位大写字母，一位小写字母和一位特殊字符）");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addComponent(jButton3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5)
                                    .addComponent(jButton2))
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField7)
                                            .addComponent(jPasswordField1)
                                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel13))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addGap(14, 14, 14)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jLabel14)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(3, 3, 3)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //点击注册按钮
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //首先要检查语法问题，例如学号，姓名，班级和邮箱的格式。
        String NO = jTextField3.getText().trim();
        String Name = jTextField4.getText().trim();
        String Class = jTextField5.getText().trim();
        String Email =  jTextField6.getText().trim();
        String OrignalClass = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        //然后在收集注册的内容信息，发送给服务器
        
        String verStr =  Verify(NO,Name,Email);
        if(verStr.length() > 4)
        {
            JOptionPane.showMessageDialog(null, verStr, "信息错误", JOptionPane.ERROR_MESSAGE);
        }else //表示不存在输入语法错误信息
        {
            //开始注册，将学号，姓名，班级，邮箱地址，实际班级等信息发送到服务器进行注册
            String regInfo = NO+"-"+Name+"-"+Class+"-"+Email+"-"+OrignalClass; //以“-”号进行分隔
            
            int sarRetFlag = SendAndRegister(regInfo); //返回三个信息，1 2,-1
            System.out.println("Register return value is :" + sarRetFlag);
            
            if(sarRetFlag ==1)
            {
                JOptionPane.showMessageDialog(null, ""+Name+"同学注册成功!","OK", JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                if(sarRetFlag == 2)
                {
                    JOptionPane.showMessageDialog(null,  ""+Name+"同学已经存在，无法重复注册!","Fail", JOptionPane.ERROR_MESSAGE);
                }else
                {
                    JOptionPane.showMessageDialog(null,  ""+Name+"同学注册失败!", "Fail",JOptionPane.ERROR_MESSAGE);
                }
            }
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //针对修改密码的格式校验
    public String Verify(String NO, String Email,String oldPassword, String newPassword)
    {
        StringBuffer retStr = new StringBuffer("");
        if(VerifyNO(NO)== false)
        {
            retStr.append("学号格式不正确，请重新输入！");
        }
        if(VerifyEmail(Email) == false)
        {
            retStr.append(  "请输入正确的EMAIl地址！") ;
        }
        if(VerifyPassword(oldPassword) == false)
        {
            retStr.append(  "请输入正确格式的旧密码！") ;
        }
         if(VerifyPassword(newPassword) == false)
        {
            retStr.append(  "请输入正确格式的新密码！") ;
        }
        
        return retStr.toString();
    }
    
    public boolean VerifyPassword(String Password)
    {//验证密码格式，至少一位小写字母，至少一位大写字母，至少一位数字，至少一位特殊字符，8-12位
        
        char[]  passChar = new char[Password.length()];
        
        for(int i=0;i<Password.length();i++)
        {
            passChar[i] = Password.charAt(i);
        }
        
        if((Password.length()>12)||(Password.length()<8))
        {
            return false;
        }
        
        //判断至少有一个特殊字符
        String specialChar = "~!@#$%^&[]()*_+=`|:;'><?/";
        boolean specialFlag = false;
        for(int i=0;i<Password.length();i++)
        {
            if(specialChar.indexOf(passChar[i]) !=-1)
            {
                specialFlag = true;
                break;
            }
        }
        //判断至少有一个小写字母
        boolean lowerFlag = false;
        for(int i=0;i<Password.length();i++)
        {
            if((passChar[i]<='z') && (passChar[i]>='a'))
            {
                lowerFlag = true;
                break;
            }
        }
        //判断至少有一个大写字母
        boolean upperFlag = false;
        for(int i=0;i<Password.length();i++)
        {
            if((passChar[i]<='Z') && (passChar[i]>='A'))
            {
                upperFlag = true;
                break;
            }
        }
        //判断至少有一个数字
        boolean numFlag = false;
        for(int i=0;i<Password.length();i++)
        {
            if((passChar[i]<='9') && (passChar[i]>='0'))
            {
                numFlag = true;
                break;
            }
        }
        
        return(specialFlag && lowerFlag && upperFlag && numFlag);
        
    }
    public String Verify(String NO, String Name, String Email)
    {
        StringBuffer retStr = new StringBuffer("");
        if(VerifyNO(NO)== false)
        {
            retStr.append("学号格式不正确，请重新输入！");
        }
        if(VerifyName(Name) == false)
        {
            retStr.append(  "请输入正确的姓名！") ;
        }
        if(VerifyEmail(Email) == false)
        {
            retStr.append(  "请输入正确的EMAIl地址。") ;
        }
        return retStr.toString();
    }
    
    public boolean VerifyName(String Name)
    {
        try
        {
            if(Name.length() > 12)
            {
                return false;
            }
        }catch(Exception e)
        {
            e.printStackTrace();
            return false;
        }
        return true;
    }
    
    
    
    public boolean VerifyNO(String NO)
    {//学号要求是11位的整数
        try
        {
            if(NO.length() != 11)
            {
                return false;
            }
            char[] charNO = new char[11];
            for(int i=0;i<11;i++)
            {
                charNO[i] = NO.charAt(i);
                if((charNO[i]>'9')||(charNO[i]<'0'))
                {
                    return false;
                }
            }
        }catch(Exception e)
        {   
            e.printStackTrace();
            return false;
        }
        return true;
    }
    
    public boolean VerifyEmail(String Email)
    {
        //abcd@163.com
        if(Email.contains("@163.com") == false)
        {
            return false;
        }
        
        int length = Email.length();
        String lastStr = Email.substring(length-8, length);
        System.out.println("Email is :" + lastStr);
        if(lastStr.equalsIgnoreCase("@163.com"))
        {
            
            return true;
        }
        return false;
    }
    
    
    //发送注册信息，并等待服务器返回信息，如果返回为”1“，表示修改成功，"2"否则修改失败，因为输入的ID，邮箱或者旧密码不正确；
    //其他表示注册失败，原因待查
    public int SendAndModifyPassword(String msg)
    {
        pw.println(msg);//输出字符流，由Socket调用系统底层函数，经网卡发送字节流
        if(receive().equalsIgnoreCase("1"))
        {
            return 1;
        }else
        {
            return 2;
        }
    }
    
    //发送注册信息，并等待服务器返回信息，如果返回为”1“，表示注册成功，"2"否则注册失败，因为该用户已经注册；
    //其他表示注册失败，原因待查
    public int SendAndRegister(String msg)
    {
        pw.println(msg);//输出字符流，由Socket调用系统底层函数，经网卡发送字节流
        String retStr = receive();
        if(retStr.equalsIgnoreCase("1"))
        {
            return 1;
        }else
        {
            if(retStr.equalsIgnoreCase("2"))
            {
                return 2;
            }else
                return 3;
        }
    }
    
    public String receive()
    {
        String msg;
        try
        {
            System.out.println("CLientJFrame等待接收");
            msg = br.readLine();//从网络输入字符流中读信息，每次只能接受一行信息
            System.out.println("CLientJFrame接收到： " + msg);
            //如果不够一行（无行结束符），则该语句阻塞，直到条件满足，程序才往下运行
        }catch(Exception e)
        {
            msg = null;
            e.printStackTrace();
        }
        return msg;
    }
    
    
    //点击修改密码按钮
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //首先校验输入信息的合法性，然后校验两次新密码的合法性和一致性
        String NO = jTextField7.getText();
        String Email = jTextField8.getText();
        
        String oldPassword = jPasswordField1.getText();
        String newPassword = jPasswordField2.getText();
        String newPasswordRepeat =jPasswordField3.getText();
        
        if(newPassword.equals(newPasswordRepeat) == false)//两次输入的密码新不一致
        {
            JOptionPane.showMessageDialog(null, "两次输入的密码不一致！", "Alert", JOptionPane.ERROR_MESSAGE);
            jPasswordField3.setText("");
            return;
        }
        
        
        //下面校验学号，email的格式，以及新密码的格式，
         String verStr =  Verify(NO,Email,oldPassword,newPassword);
         if(verStr.length() > 4)
         {
             JOptionPane.showMessageDialog(null, "输入信息错误："+verStr,"Alert", JOptionPane.ERROR_MESSAGE);
         }else
         {//所有格式均正确
             //开始修改密码，将学号，邮箱地址，旧密码，新密码等信息发送到服务器进行注册
            String modifyPasswordInfo = NO+"-"+Email+"-"+oldPassword+"-"+newPassword; //以“-”号进行分隔
            
            int mpRetFlag = SendAndModifyPassword(modifyPasswordInfo); //返回三个信息，1 2
            
            if(mpRetFlag ==1)
            {
                JOptionPane.showMessageDialog(null,  "密码修改成功!", "OK",JOptionPane.INFORMATION_MESSAGE);
            }else
            {
                JOptionPane.showMessageDialog(null, "学号，邮箱或旧密码信息错误，修改失败!","Fail",JOptionPane.ERROR_MESSAGE);
            }
             
         }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    
    //点击连接服务器按钮
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ip = jTextField1.getText();
        String port = jTextField2.getText();
        
        try
        {
            socket = new Socket(ip,Integer.parseInt(port));
        
            //主动向服务器发起连接，实现TCP的三次握手过程
            //如果不成功，则抛出错误信息，其错误信息交由调用者处理
            //如果成功，则做如下两件事情
        
            OutputStream socketOut = socket.getOutputStream();
            pw = new PrintWriter(new OutputStreamWriter(socketOut,"GB2312"),true);
            //得到网络输出字节流地址，并封装成网络输出字符流
        
            InputStream socketIn = socket.getInputStream();
            br = new BufferedReader(new InputStreamReader(socketIn,"GB2312"));
            //得到网络输入字节流地址，并封装成网络输入字符流
            
            //连接成功，显示连接成功提示，同时激活下面的注册和修改密码的部分
            
            jLabel15.setText("连接服务器成功！");
            
            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField7.setEnabled(true);
            jTextField8.setEnabled(true);
            jComboBox1.setEnabled(true);
            jButton1.setEnabled(true);
            jButton4.setEnabled(true);
            
            jPasswordField1.setEnabled(true);
            jPasswordField2.setEnabled(true);
            jPasswordField3.setEnabled(true);
            
            
            
        }catch(Exception e)
        {
            jTextField3.setEnabled(false);
            jTextField4.setEnabled(false);
            jTextField5.setEnabled(false);
            jTextField6.setEnabled(false);
            jTextField7.setEnabled(false);
            jTextField8.setEnabled(false);
            jComboBox1.setEnabled(false);
            jButton1.setEnabled(false);
            jButton4.setEnabled(false);
            
            jPasswordField1.setEnabled(false);
            jPasswordField2.setEnabled(false);
            jPasswordField3.setEnabled(false);
            
            jLabel15.setText("连接服务器失败！");
            System.out.println("连接服务器失败。");
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(socket != null)
            {
                socket.close();
            }
            System.exit(0);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         try
        {
            if(socket != null)
            {
                socket.close();
            }
            System.exit(0);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAndPasswordModifyClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAndPasswordModifyClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAndPasswordModifyClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAndPasswordModifyClientJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAndPasswordModifyClientJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}





